.TH LOOLWSD-SYSTEMPLATE-SETUP "1" "May 2018" "oxoolwsd-systemplate-setup " "User Commands"
.SH NAME
oxoolwsd-systemplate-setup
.SH SYNOPSYS
oxoolwsd-systemplate-setup <chroot template directory for system libs to create> <OxOffice installation directory>
.SH DESCRIPTION
oxoolwsd-systemplate-setup creates a minimal system template for running the LibreOfficeKit in a chroot jail. The system template contains the bare minimum of system libraries to run LibreOfficeKit, and also fonts and locale data from the system.
.SH "SEE ALSO"
oxoolforkit(1), oxoolconvert(1), oxoolconfig(1), oxoolwsd(1), oxoolwsd-generate-proof-key(1)
