.TH LOOLCONVERT "1" "May 2018" "oxoolconvert" "User Commands"
.SH NAME
oxoolconvert \- OxOffice Online document converter tool
.SH SYNOPSYS
oxoolconvert OPTIONS FILE(S)
.SH OPTIONS
\fB\-\-help\fR                  Display help information on command line arguments.
.PP
\fB\-\-extension\fR=\fIformat\fR      file format extension to convert to
.PP
\fB\-\-outdir\fR=\fIoutdir\fR         output directory for converted files
.PP
\fB\-\-parallelism\fR=\fIthreads\fR   number of simultaneous threads to use
.PP
\fB\-\-server\fR=\fIuri\fR            URI of OxOOL server
.PP
\fB\-\-no\-check\-certificate\fR  Disable checking of SSL certs
.PP
.SH "SEE ALSO"
oxoolwsd(1), oxoolforkit(1), oxoolconfig(1), oxoolwsd-systemplate-setup(1), oxoolwsd-generate-proof-key(1)
