.TH LOOLWSD-GENERATE_PROOF_KEY "1" "April 2020" "oxoolwsd-generate-proof-key " "User Commands"
.SH NAME
oxoolwsd-generate-proof-key
.SH SYNOPSYS
oxoolwsd-generate-proof-key
.SH DESCRIPTION
oxoolwsd-generate-proof-key creates an RSA key pair in /etc/oxool for the WOPI Proof headers. The script is automatically run by the postinstall script of oxoolwsd package, but in case of failure sysadmins can run it manually.
.SH "SEE ALSO"
oxoolforkit(1), oxoolconvert(1), oxoolconfig(1), oxoolwsd(1), oxoolwsd-systemplate-setup(1)
