#!/bin/sh
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


# Enable Extra Packages for Enterprise Linux repository
dnf install epel-release -y

# Enable PowerTools repository
dnf config-manager --set-enabled powertools

# Install cpio (missing dependency needed by oxoolwsd-systemplate-setup)
dnf install -y cpio

# Install gnupg2
dnf install -y gnupg2

# install ca-certificates
dnf install -y ca-certificates

# install ssh-keygen binary for the WOPI proof key
dnf install -y openssh

# Install curl for simple healthchecks and wget
dnf install -y curl wget

# Add OxOffice Online Community repos
dnf config-manager --add-repo http://www.oxoffice.com.tw/rpm/el/oxool-community-v4-el8.repo

# Install the OxOffice Online Community packages
dnf groupinstall "OxOOL Community Group" -y

# Install inotifywait and killall to automatic restart oxoolwsd, if oxoolwsd.xml changes
dnf install -y inotify-tools psmisc perl

# Upgrade all packages
dnf upgrade -y

# Cleanup
dnf clean all

# Remove WOPI Proof key generated by the package, we need unique key for each container
rm -rf /etc/oxool/proof_key*

# Fix permissions
# cf. start-oxoffice-online.sh that is run by lool user
# # Fix domain name resolution from jails
# cp /etc/resolv.conf /etc/hosts /opt/oxool/systemplate/etc/
chown lool:lool /opt/oxool/systemplate/etc/hosts /opt/oxool/systemplate/etc/resolv.conf
# generated ssl cert/key and WOPI proof key go into /etc/oxool
chown lool:lool /etc/oxool
