FROM centos:7

RUN yum update -y
RUN yum install vim net-tools unzip wget -y
RUN wget --no-check-certificate http://www.oxoffice.com.tw/yum.repo/oxool-community.repo -P /etc/yum.repos.d/
RUN yum update -y
RUN yum groupinstall "OxOOL Community Group" -y
RUN localedef -c -f UTF-8 -i zh_TW zh_TW.utf8

RUN echo 'LANG="zh_TW.UTF-8"' > /etc/locale.conf
ENV LANG zh_TW.UTF-8
ENV LC_ALL zh_TW.UTF-8

EXPOSE 9980

# switch to lool user (use numeric user id to be compatible with Kubernetes Pod Security Policies)
USER lool

CMD /usr/bin/oxool
